import { Inter } from "next/font/google";
import "@/style/globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import ReduxProvider from "@/redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CookMaster",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`${inter.className}`}>
          <Header />
          {children}
          <Footer />
        </body>
      </ReduxProvider>
    </html>
  );
}
